### ISSUE TITLE
can't use gateway 

### ISSUE THREAD

**Issue by osindex** [wechaty/puppet-padlocal#117]
wechaty/wechaty:1.10

```
05:44:10 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"Wechaty Puppet gRPC stream connect successfully"})
05:44:10 VERB PuppetServiceImpl start()
05:44:10 ERR PuppetServiceImpl grpcError() start() rejection: The "listener" argument must be of type function. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (node:events:128:3)
    at _addListener (node:events:423:3)
    at StateSwitch.addListener (node:events:487:10)
    at PuppetPadlocal._startClient (/wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:145:20)
    at PuppetPadlocal.start (/wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:141:16)
    at start (file:///wechaty/node_modules/wechaty-puppet-service/src/server/puppet-implementation.ts:1332:18)
    at Object.start (file:///wechaty/node_modules/wechaty-puppet-service/src/auth/auth-impl-token.ts:49:18)
    at handleUnary (/wechaty/node_modules/@grpc/grpc-js/src/server.ts:896:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by osindex** [comment]
docker-compose.yml
```
version: "3.2"
services:
        wechaty_puppet_service_token_gateway:
                image: "wechaty/wechaty:1.10"
                env_file:
                 - env.gateway
                ports:
                 - "8788:8788"
                restart: always
                tty: true
```
env.gateway
```
WECHATY_LOG=verbose
WECHATY_PUPPET=wechaty-puppet-padlocal
WECHATY_PUPPET_SERVER_PORT=8788
WECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_**
WECHATY_TOKEN=puppet_padlocal_**
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true
```
